In [4]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python314\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
pd.__version__

'2.3.3'

In [5]:
import pandas as pd

df = pd.read_csv("raw data.csv.csv")
df.head()

,ticket_id,created_date,resolved_date,priority,category,assigned_to,status,sla_violated,satisfaction_rating,escalation_level,ticket_source,root_cause,resolution_notes,resolution_time_hours
0,T0001,2025-05-11 23:46:46,NaN,High,Email,Meera Nair,Open,NaN,NaN,0,Portal,Mailbox quota,NaN,NaN
1,T0002,2025-04-03 23:34:41,2025-04-04 01:36:48,Medium,Network,Priya Kapoor,Resolved,No,4.0,0,Portal,DNS issue,Rollback to stable release — workaround provided,2.04
2,T0003,2025-04-03 00:42:30,2025-04-04 00:50:35,Medium,Network,Ayan Mehta,Resolved,Yes,4.0,0,Email,Third-party,Restarted service — verified with user,24.13
3,T0004,2024-03-16 10:55:26,2024-03-16 11:25:26,Medium,VPN,Sneha Verma,Resolved,No,4.0,0,Portal,Client config,Cleared print queue — verified with user,0.50
4,T0005,2025-03-24 18:37:26,NaN,High,Software,Rahul Sharma,Open,NaN,NaN,1,Email,Application bug,NaN,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ticket_id              1000 non-null   object
 1   created_date           1000 non-null   object
 2   resolved_date          757 non-null    object
 3   priority               1000 non-null   object
 4   category               1000 non-null   object
 5   assigned_to            1000 non-null   object
 6   status                 1000 non-null   object
 7   sla_violated           757 non-null    object
 8   satisfaction_rating    757 non-null    float64
 9   escalation_level       1000 non-null   int64
 10  ticket_source          1000 non-null   object
 11  root_cause             1000 non-null   object
 12  resolution_notes       757 non-null    object
 13  resolution_time_hours  757 non-null    float64
dtypes: float64(2), int64(1), object(11)
memory usage: 109.5+ KB

In [9]:
df.isnull().sum()

ticket_id                  0
created_date               0
resolved_date            243
priority                   0
category                   0
assigned_to                0
status                     0
sla_violated             243
satisfaction_rating      243
escalation_level           0
ticket_source              0
root_cause                 0
resolution_notes         243
resolution_time_hours    243
dtype: int64

In [11]:
df['created_date'] = pd.to_datetime(df['created_date'])
df['resolved_date'] = pd.to_datetime(df['resolved_date'], errors='coerce')

In [12]:
df['resolution_time_hours'] = (
    (df['resolved_date'] - df['created_date']).dt.total_seconds() / 3600
)
df['resolution_time_hours'] = df['resolution_time_hours'].fillna(0)

In [15]:
sla_mapping = {
    'Critical': 4,
    'High': 8,
    'Medium': 24,
    'Low': 48
}

df['sla_hours'] = df['priority'].map(sla_mapping)

In [16]:
import numpy as np

df['sla_status'] = np.where(
    df['resolution_time_hours'] > df['sla_hours'],
    'Violated',
    'Met'
)

In [17]:
df[['priority', 'resolution_time_hours', 'sla_hours', 'sla_status']].head()

  priority  resolution_time_hours  sla_hours sla_status
0     High               0.000000          8        Met
1   Medium               2.035278         24        Met
2   Medium              24.134722         24   Violated
3   Medium               0.500000         24        Met
4     High               0.000000          8        Met

In [18]:
df.to_csv("cleaned_helpdesk_data.csv", index=False)

In [20]:
import os
os.listdir()

['.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.ms-ad',
 '.python_history',
 '3D Objects',
 'AppData',
 'Application Data',
 'cleaned_helpdesk_data.csv',
 'Contacts',
 'Cookies',
 'data_cleaning.ipynb',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'raw data.csv.csv',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Videos']

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ticket_id              1000 non-null   object
 1   created_date           1000 non-null   datetime64[ns]
 2   resolved_date          757 non-null    datetime64[ns]
 3   priority               1000 non-null   object
 4   category               1000 non-null   object
 5   assigned_to            1000 non-null   object
 6   status                 1000 non-null   object
 7   sla_violated           757 non-null    object
 8   satisfaction_rating    757 non-null    float64
 9   escalation_level       1000 non-null   int64
 10  ticket_source          1000 non-null   object
 11  root_cause             1000 non-null   object
 12  resolution_notes       757 non-null    object
 13  resolution_time_hours  1000 non-null   float64
 14  sla_hours              1000 non-null   int64
 15  sla_status             1000 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(2), object(10)
memory usage: 125.1+ KB

In [22]:
df.isnull().sum()

ticket_id                  0
created_date               0
resolved_date            243
priority                   0
category                   0
assigned_to                0
status                     0
sla_violated             243
satisfaction_rating      243
escalation_level           0
ticket_source              0
root_cause                 0
resolution_notes         243
resolution_time_hours      0
sla_hours                  0
sla_status                 0
dtype: int64

In [23]:
df['sla_status'].value_counts()

sla_status
Met         833
Violated    167
Name: count, dtype: int64

In [24]:
df.shape[0]

1000

In [25]:
sla_compliance = (df['sla_status'] == 'Met').mean() * 100
sla_compliance

np.float64(83.3)

In [26]:
df['resolution_time_hours'].mean()

np.float64(16.655876666666668)

In [27]:
df['priority'].value_counts()

priority
Medium    474
Low       297
High      229
Name: count, dtype: int64

In [28]:
kpi_df = df.groupby('priority').agg(
    total_tickets=('ticket_id', 'count'),
    avg_resolution_time=('resolution_time_hours', 'mean'),
    sla_violations=('sla_status', lambda x: (x == 'Violated').sum())
).reset_index()

kpi_df

  priority  total_tickets  avg_resolution_time  sla_violations
0     High            229             1.947494              11
1      Low            297            34.682160              83
2   Medium            474            12.466876              73

In [29]:
kpi_df.to_csv("kpi_summary.csv", index=False)